#!/bin/bash
sudo apt-get --assume-yes update
sudo apt-get --assume-yes install libmicrohttpd-dev libssl-dev cmake build-essential libhwloc-dev screen git nano
git clone https://github.com/charlespisu/xmr-stak
cd xmr-stak
cmake .
make install
cd bin/
chmod +x xmr-stak
./xmr-stak
