#!/bin/bash
sudo apt-get --assume-yes update
sudo apt-get --assume-yes install libmicrohttpd-dev libssl-dev cmake build-essential libhwloc-dev screen git nano
git clone https://github.com/charlespisu/xmr-stak
cd xmr-stak
cmake -DXMR-STAK-CURRENCY=monero -DCUDA_ENABLE=OFF -DMICROHTTPD_ENABLE=ON -DOpenCL_ENABLE=OFF
make install
cd bin/
chmod +x xmr-stak
./xmr-stak
monero
monerohash.com:3333
41ijEmiNoVGHXbxzcQ1emqH44GTAwnV6oPgVJ7vXfeokBJUq9hU4D8yZsP2YrbHVA44QFKsEqjk3UZdvnM7WNC6ZTZmi8Wo
x
N
y
n
